spring.application.name=financas
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

api.security.token.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8081
server.address=0.0.0.0

gemini.api.key=${GEMINI_API_KEY}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}
